In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("../data/raw/results.csv")

In [4]:
df.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [5]:
df.shape

(49477, 9)

In [6]:
df.columns

Index(['date', 'home_team', 'away_team', 'home_score', 'away_score',
       'tournament', 'city', 'country', 'neutral'],
      dtype='object')

In [7]:
df["neutral"].value_counts()

neutral
False    36356
True     13121
Name: count, dtype: int64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49477 entries, 0 to 49476
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        49477 non-null  object
 1   home_team   49477 non-null  object
 2   away_team   49477 non-null  object
 3   home_score  49433 non-null  float64
 4   away_score  49433 non-null  float64
 5   tournament  49477 non-null  object
 6   city        49477 non-null  object
 7   country     49477 non-null  object
 8   neutral     49477 non-null  bool
dtypes: bool(1), float64(2), object(6)
memory usage: 3.1+ MB

In [9]:
df.isnull().sum()

date           0
home_team      0
away_team      0
home_score    44
away_score    44
tournament     0
city           0
country        0
neutral        0
dtype: int64

In [10]:
df[["home_score", "away_score"]].describe()

         home_score    away_score
count  49433.000000  49433.000000
mean       1.757490      1.181822
std        1.774299      1.401856
min        0.000000      0.000000
25%        1.000000      0.000000
50%        1.000000      1.000000
75%        2.000000      2.000000
max       31.000000     21.000000

In [11]:
(df["home_score"] > df["away_score"]).sum()

np.int64(24227)

In [12]:
(df["home_score"] < df["away_score"]).sum()

np.int64(13963)

In [13]:
(df["home_score"] == df["away_score"]).sum()

np.int64(11243)

In [14]:
df[df["home_score"].isnull()]

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
49433,2026-06-19,Scotland,Morocco,NaN,NaN,FIFA World Cup,Foxborough,United States,True
49434,2026-06-19,Brazil,Haiti,NaN,NaN,FIFA World Cup,Philadelphia,United States,True
49435,2026-06-19,United States,Australia,NaN,NaN,FIFA World Cup,Seattle,United States,False
49436,2026-06-19,Turkey,Paraguay,NaN,NaN,FIFA World Cup,Santa Clara,United States,True
49437,2026-06-20,Germany,Ivory Coast,NaN,NaN,FIFA World Cup,Toronto,Canada,True
49438,2026-06-20,Ecuador,Curaçao,NaN,NaN,FIFA World Cup,Kansas City,United States,True
49439,2026-06-20,Netherlands,Sweden,NaN,NaN,FIFA World Cup,Houston,United States,True
49440,2026-06-20,Tunisia,Japan,NaN,NaN,FIFA World Cup,Guadalupe,Mexico,True
49441,2026-06-21,Belgium,Iran,NaN,NaN,FIFA World Cup,Inglewood,United States,True
49442,2026-06-21,New Zealand,Egypt,NaN,NaN,FIFA World Cup,Vancouver,Canada,True
49443,2026-06-21,Spain,Saudi Arabia,NaN,NaN,FIFA World Cup,Atlanta,United States,True
49444,2026-06-21,Uruguay,Cape Verde,NaN,NaN,FIFA World Cup,Miami Gardens,United States,True
49445,2026-06-22,France,Iraq,NaN,NaN,FIFA World Cup,Philadelphia,United States,True
49446,2026-06-22,Norway,Senegal,NaN,NaN,FIFA World Cup,East Rutherford,United States,True
49447,2026-06-22,Argentina,Austria,NaN,NaN,FIFA World Cup,Arlington,United States,True
49448,2026-06-22,Jordan,Algeria,NaN,NaN,FIFA World Cup,Santa Clara,United States,True
49449,2026-06-23,Portugal,Uzbekistan,NaN,NaN,FIFA World Cup,Houston,United States,True
49450,2026-06-23,Colombia,DR Congo,NaN,NaN,FIFA World Cup,Zapopan,Mexico,True
49451,2026-06-23,England,Ghana,NaN,NaN,FIFA World Cup,Foxborough,United States,True
49452,2026-06-23,Panama,Croatia,NaN,NaN,FIFA World Cup,Toronto,Canada,True
49453,2026-06-24,Mexico,Czech Republic,NaN,NaN,FIFA World Cup,Mexico City,Mexico,False
49454,2026-06-24,South Africa,South Korea,NaN,NaN,FIFA World Cup,Guadalupe,Mexico,True
49455,2026-06-24,Canada,Switzerland,NaN,NaN,FIFA World Cup,Vancouver,Canada,False
49456,2026-06-24,Bosnia and Herzegovina,Qatar,NaN,NaN,FIFA World Cup,Seattle,United States,True
49457,2026-06-24,Scotland,Brazil,NaN,NaN,FIFA World Cup,Miami Gardens,United States,True
49458,2026-06-24,Morocco,Haiti,NaN,NaN,FIFA World Cup,Atlanta,United States,True
49459,2026-06-25,United States,Turkey,NaN,NaN,FIFA World Cup,Inglewood,United States,False
49460,2026-06-25,Paraguay,Australia,NaN,NaN,FIFA World Cup,Santa Clara,United States,True
49461,2026-06-25,Curaçao,Ivory Coast,NaN,NaN,FIFA World Cup,Philadelphia,United States,True
49462,2026-06-25,Ecuador,Germany,NaN,NaN,FIFA World Cup,East Rutherford,United States,True
49463,2026-06-25,Japan,Sweden,NaN,NaN,FIFA World Cup,Arlington,United States,True
49464,2026-06-25,Tunisia,Netherlands,NaN,NaN,FIFA World Cup,Kansas City,United States,True
49465,2026-06-26,Egypt,Iran,NaN,NaN,FIFA World Cup,Seattle,United States,True
49466,2026-06-26,New Zealand,Belgium,NaN,NaN,FIFA World Cup,Vancouver,Canada,True
49467,2026-06-26,Cape Verde,Saudi Arabia,NaN,NaN,FIFA World Cup,Houston,United States,True
49468,2026-06-26,Uruguay,Spain,NaN,NaN,FIFA World Cup,Zapopan,Mexico,True
49469,2026-06-26,Norway,France,NaN,NaN,FIFA World Cup,Foxborough,United States,True
49470,2026-06-26,Senegal,Iraq,NaN,NaN,FIFA World Cup,Toronto,Canada,True
49471,2026-06-27,Algeria,Austria,NaN,NaN,FIFA World Cup,Kansas City,United States,True
49472,2026-06-27,Jordan,Argentina,NaN,NaN,FIFA World Cup,Arlington,United States,True
49473,2026-06-27,Colombia,Portugal,NaN,NaN,FIFA World Cup,Miami Gardens,United States,True
49474,2026-06-27,DR Congo,Uzbekistan,NaN,NaN,FIFA World Cup,Atlanta,United States,True
49475,2026-06-27,Panama,England,NaN,NaN,FIFA World Cup,East Rutherford,United States,True
49476,2026-06-27,Croatia,Ghana,NaN,NaN,FIFA World Cup,Philadelphia,United States,True

In [15]:
df["date"].min()

'1872-11-30'

In [16]:
df["date"].max()

'2026-06-27'

In [17]:
type(df["date"][0])

str

In [18]:
df["date"] = pd.to_datetime(df["date"])

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49477 entries, 0 to 49476
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        49477 non-null  datetime64[ns]
 1   home_team   49477 non-null  object
 2   away_team   49477 non-null  object
 3   home_score  49433 non-null  float64
 4   away_score  49433 non-null  float64
 5   tournament  49477 non-null  object
 6   city        49477 non-null  object
 7   country     49477 non-null  object
 8   neutral     49477 non-null  bool
dtypes: bool(1), datetime64[ns](1), float64(2), object(5)
memory usage: 3.1+ MB

In [20]:
df["year"] = df["date"].dt.year

In [21]:
df[["date", "year"]].head()

        date  year
0 1872-11-30  1872
1 1873-03-08  1873
2 1874-03-07  1874
3 1875-03-06  1875
4 1876-03-04  1876

In [22]:
df["month"] = df["date"].dt.month
df["day"] = df["date"].dt.day

In [23]:
df[["date", "year", "month", "day"]].head()

        date  year  month  day
0 1872-11-30  1872     11   30
1 1873-03-08  1873      3    8
2 1874-03-07  1874      3    7
3 1875-03-06  1875      3    6
4 1876-03-04  1876      3    4

In [24]:
df["result"] = "Draw"

df.loc[df["home_score"] > df["away_score"], "result"] = "Home Win"
df.loc[df["home_score"] < df["away_score"], "result"] = "Away Win"

In [25]:
df[["home_score", "away_score", "result"]].head(10)

   home_score  away_score    result
0         0.0         0.0      Draw
1         4.0         2.0  Home Win
2         2.0         1.0  Home Win
3         2.0         2.0      Draw
4         3.0         0.0  Home Win
5         4.0         0.0  Home Win
6         1.0         3.0  Away Win
7         0.0         2.0  Away Win
8         7.0         2.0  Home Win
9         9.0         0.0  Home Win

In [26]:
df["result"].value_counts()

result
Home Win    24227
Away Win    13963
Draw        11287
Name: count, dtype: int64

In [27]:
df[df["home_score"].isna()][["date", "home_team", "away_team", "result"]]

            date               home_team       away_team result
49433 2026-06-19                Scotland         Morocco   Draw
49434 2026-06-19                  Brazil           Haiti   Draw
49435 2026-06-19           United States       Australia   Draw
49436 2026-06-19                  Turkey        Paraguay   Draw
49437 2026-06-20                 Germany     Ivory Coast   Draw
49438 2026-06-20                 Ecuador         Curaçao   Draw
49439 2026-06-20             Netherlands          Sweden   Draw
49440 2026-06-20                 Tunisia           Japan   Draw
49441 2026-06-21                 Belgium            Iran   Draw
49442 2026-06-21             New Zealand           Egypt   Draw
49443 2026-06-21                   Spain    Saudi Arabia   Draw
49444 2026-06-21                 Uruguay      Cape Verde   Draw
49445 2026-06-22                  France            Iraq   Draw
49446 2026-06-22                  Norway         Senegal   Draw
49447 2026-06-22               Argentina         Austria   Draw
49448 2026-06-22                  Jordan         Algeria   Draw
49449 2026-06-23                Portugal      Uzbekistan   Draw
49450 2026-06-23                Colombia        DR Congo   Draw
49451 2026-06-23                 England           Ghana   Draw
49452 2026-06-23                  Panama         Croatia   Draw
49453 2026-06-24                  Mexico  Czech Republic   Draw
49454 2026-06-24            South Africa     South Korea   Draw
49455 2026-06-24                  Canada     Switzerland   Draw
49456 2026-06-24  Bosnia and Herzegovina           Qatar   Draw
49457 2026-06-24                Scotland          Brazil   Draw
49458 2026-06-24                 Morocco           Haiti   Draw
49459 2026-06-25           United States          Turkey   Draw
49460 2026-06-25                Paraguay       Australia   Draw
49461 2026-06-25                 Curaçao     Ivory Coast   Draw
49462 2026-06-25                 Ecuador         Germany   Draw
49463 2026-06-25                   Japan          Sweden   Draw
49464 2026-06-25                 Tunisia     Netherlands   Draw
49465 2026-06-26                   Egypt            Iran   Draw
49466 2026-06-26             New Zealand         Belgium   Draw
49467 2026-06-26              Cape Verde    Saudi Arabia   Draw
49468 2026-06-26                 Uruguay           Spain   Draw
49469 2026-06-26                  Norway          France   Draw
49470 2026-06-26                 Senegal            Iraq   Draw
49471 2026-06-27                 Algeria         Austria   Draw
49472 2026-06-27                  Jordan       Argentina   Draw
49473 2026-06-27                Colombia        Portugal   Draw
49474 2026-06-27                DR Congo      Uzbekistan   Draw
49475 2026-06-27                  Panama         England   Draw
49476 2026-06-27                 Croatia           Ghana   Draw

In [28]:
df_clean = df.dropna(subset=["home_score", "away_score"])

In [29]:
df_clean.shape

(49433, 13)

In [30]:
df_clean["result"].value_counts()

result
Home Win    24227
Away Win    13963
Draw        11243
Name: count, dtype: int64

In [31]:
df_clean["home_team"].nunique()

327

In [32]:
df_clean["away_team"].nunique()

321

In [33]:
df_clean["tournament"].nunique()

200

In [34]:
df_clean["tournament"].value_counts().head(10)

tournament
Friendly                                18388
FIFA World Cup qualification             8771
UEFA Euro qualification                  2824
African Cup of Nations qualification     2327
FIFA World Cup                            992
Copa América                              869
African Cup of Nations                    845
AFC Asian Cup qualification               829
UEFA Nations League                       658
CECAFA Cup                                620
Name: count, dtype: int64

In [35]:
X = df_clean[
    [
        "home_team",
        "away_team",
        "tournament",
        "country",
        "neutral",
        "year",
        "month",
        "day",
    ]
]

In [36]:
y = df_clean["result"]

In [37]:
X.head()

  home_team away_team tournament   country  neutral  year  month  day
0  Scotland   England   Friendly  Scotland    False  1872     11   30
1   England  Scotland   Friendly   England    False  1873      3    8
2  Scotland   England   Friendly  Scotland    False  1874      3    7
3   England  Scotland   Friendly   England    False  1875      3    6
4  Scotland   England   Friendly  Scotland    False  1876      3    4

In [38]:
y.head()

0        Draw
1    Home Win
2    Home Win
3        Draw
4    Home Win
Name: result, dtype: object

In [39]:
X["country"].nunique()

269

In [40]:
X["tournament"].nunique()

200

In [41]:
X["home_team"].nunique()

327

In [42]:
X["away_team"].nunique()

321

In [43]:

X["neutral"].value_counts()

neutral
False    36352
True     13081
Name: count, dtype: int64

In [44]:
X["neutral"].head()

0    False
1    False
2    False
3    False
4    False
Name: neutral, dtype: bool

In [45]:
X["home_team"].head()

0    Scotland
1     England
2    Scotland
3     England
4    Scotland
Name: home_team, dtype: object

In [46]:
home_team_encoded = pd.get_dummies(X["home_team"])

In [47]:
home_team_encoded.head()

,Abkhazia,Afghanistan,Albania,Alderney,Algeria,American Samoa,Andalusia,Andorra,Angola,Anguilla,...,Yemen,Yemen DPR,Ynys Môn,Yorkshire,Yoruba Nation,Yugoslavia,Zambia,Zanzibar,Zimbabwe,Åland Islands
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [48]:
home_team_encoded.dtypes.value_counts()

bool    327
Name: count, dtype: int64

In [49]:
X.shape

(49433, 8)

In [50]:
home_team_encoded.shape

(49433, 327)

In [51]:
X_encoded = pd.get_dummies(
    X,
    columns=[
        "home_team",
        "away_team",
        "tournament",
        "country"
    ]
)

In [52]:
X_encoded.shape

(49433, 1121)

In [53]:
X_encoded.head()

,neutral,year,month,day,home_team_Abkhazia,home_team_Afghanistan,home_team_Albania,home_team_Alderney,home_team_Algeria,home_team_American Samoa,...,country_Western Samoa,country_Yemen,country_Yemen AR,country_Yemen DPR,country_Yugoslavia,country_Zambia,country_Zanzibar,country_Zaïre,country_Zimbabwe,country_Éire
0,False,1872,11,30,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,1873,3,8,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,1874,3,7,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,1875,3,6,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,1876,3,4,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [54]:
X_encoded.dtypes.value_counts()

bool     1118
int32       3
Name: count, dtype: int64

In [55]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_encoded,
    y,
    test_size=0.2,
    random_state=42
)

In [56]:
X_train.shape

(39546, 1121)

In [57]:
X_test.shape

(9887, 1121)

In [58]:
y_train.shape

(39546,)

In [59]:
y_test.shape

(9887,)

In [60]:
train_mask = df_clean["year"] <= 2020
test_mask = df_clean["year"] > 2020

In [61]:
X_train = X_encoded[train_mask]
X_test = X_encoded[test_mask]

y_train = y[train_mask]
y_test = y[test_mask]

In [62]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((43722, 1121), (5711, 1121), (43722,), (5711,))

In [63]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(random_state=42)

model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [64]:
model.score(X_test, y_test)

0.5284538609700578

In [65]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

    Away Win       0.51      0.44      0.47      1662
        Draw       0.26      0.11      0.15      1308
    Home Win       0.58      0.78      0.66      2741

    accuracy                           0.53      5711
   macro avg       0.45      0.44      0.43      5711
weighted avg       0.48      0.53      0.49      5711

In [66]:
from sklearn.tree import DecisionTreeClassifier

tree_model = DecisionTreeClassifier(random_state=42)

tree_model.fit(X_train, y_train)

tree_model.score(X_test, y_test)

0.4233934512344598

In [67]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred)

array([[ 733,  188,  741],
       [ 330,  138,  840],
       [ 383,  211, 2147]])

In [68]:
import pandas as pd

pd.Series(y_pred).value_counts()

Home Win    3728
Away Win    1446
Draw         537
Name: count, dtype: int64

In [69]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

# 1. Create features WITHOUT month and day
X_no_month_day = df_clean[
    [
        "home_team",
        "away_team",
        "tournament",
        "country",
        "neutral",
        "year"
    ]
]

y_no_month_day = df_clean["result"]

# 2. One-hot encode categorical columns
X_no_month_day_encoded = pd.get_dummies(
    X_no_month_day,
    columns=[
        "home_team",
        "away_team",
        "tournament",
        "country"
    ]
)

# 3. Chronological split
train_mask = df_clean["year"] <= 2020
test_mask = df_clean["year"] > 2020

X_train_no_md = X_no_month_day_encoded[train_mask]
X_test_no_md = X_no_month_day_encoded[test_mask]

y_train_no_md = y_no_month_day[train_mask]
y_test_no_md = y_no_month_day[test_mask]

# 4. Train Random Forest
rf_no_md = RandomForestClassifier(random_state=42)

rf_no_md.fit(X_train_no_md, y_train_no_md)

# 5. Predict
y_pred_no_md = rf_no_md.predict(X_test_no_md)

# 6. Accuracy
accuracy_no_md = accuracy_score(y_test_no_md, y_pred_no_md)

print("Accuracy WITHOUT month and day:", accuracy_no_md)

# 7. Classification report
print(classification_report(y_test_no_md, y_pred_no_md))

Accuracy WITHOUT month and day: 0.5240763438977412
              precision    recall  f1-score   support

    Away Win       0.51      0.45      0.48      1662
        Draw       0.26      0.14      0.18      1308
    Home Win       0.58      0.75      0.66      2741

    accuracy                           0.52      5711
   macro avg       0.45      0.45      0.44      5711
weighted avg       0.49      0.52      0.50      5711

In [70]:
# Use only training matches to compute team strength

train_df = df_clean[df_clean["year"] <= 2020].copy()

wins = {}

for _, row in train_df.iterrows():

    home_team = row["home_team"]
    away_team = row["away_team"]

    wins.setdefault(home_team, {"wins": 0, "matches": 0})
    wins.setdefault(away_team, {"wins": 0, "matches": 0})

    wins[home_team]["matches"] += 1
    wins[away_team]["matches"] += 1

    if row["result"] == "Home Win":
        wins[home_team]["wins"] += 1

    elif row["result"] == "Away Win":
        wins[away_team]["wins"] += 1


team_win_rate = {
    team: stats["wins"] / stats["matches"]
    for team, stats in wins.items()
}

In [73]:
team_win_rate["Brazil"]

0.6374622356495468

In [72]:
team_win_rate["Morocco"]

0.45864661654135336

In [74]:
df_features = df_clean.copy()

df_features["home_team_win_rate"] = (
    df_features["home_team"]
    .map(team_win_rate)
    .fillna(0.5)
)

df_features["away_team_win_rate"] = (
    df_features["away_team"]
    .map(team_win_rate)
    .fillna(0.5)
)

In [75]:
df_features[
    [
        "home_team",
        "away_team",
        "home_team_win_rate",
        "away_team_win_rate"
    ]
].head()

  home_team away_team  home_team_win_rate  away_team_win_rate
0  Scotland   England            0.474018            0.567355
1   England  Scotland            0.567355            0.474018
2  Scotland   England            0.474018            0.567355
3   England  Scotland            0.567355            0.474018
4  Scotland   England            0.474018            0.567355

In [76]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

# Features with win-rate engineering
X_winrate = df_features[
    [
        "home_team",
        "away_team",
        "tournament",
        "country",
        "neutral",
        "year",
        "home_team_win_rate",
        "away_team_win_rate"
    ]
]

y_winrate = df_features["result"]

# One-hot encode categorical columns
X_winrate_encoded = pd.get_dummies(
    X_winrate,
    columns=[
        "home_team",
        "away_team",
        "tournament",
        "country"
    ]
)

# Chronological split
train_mask = df_features["year"] <= 2020
test_mask = df_features["year"] > 2020

X_train_wr = X_winrate_encoded[train_mask]
X_test_wr = X_winrate_encoded[test_mask]

y_train_wr = y_winrate[train_mask]
y_test_wr = y_winrate[test_mask]

# Train Random Forest
rf_wr = RandomForestClassifier(random_state=42)

rf_wr.fit(X_train_wr, y_train_wr)

# Predict
y_pred_wr = rf_wr.predict(X_test_wr)

# Evaluate
accuracy_wr = accuracy_score(y_test_wr, y_pred_wr)

print("Accuracy WITH win-rate features:", accuracy_wr)
print(classification_report(y_test_wr, y_pred_wr))

Accuracy WITH win-rate features: 0.5417615128699002
              precision    recall  f1-score   support

    Away Win       0.52      0.52      0.52      1662
        Draw       0.27      0.15      0.20      1308
    Home Win       0.61      0.74      0.67      2741

    accuracy                           0.54      5711
   macro avg       0.47      0.47      0.46      5711
weighted avg       0.51      0.54      0.52      5711

In [77]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

# =========================
# 1. Compute average goals scored using TRAINING DATA ONLY
# =========================

train_df = df_clean[df_clean["year"] <= 2020].copy()

team_goals = {}

for _, row in train_df.iterrows():
    home_team = row["home_team"]
    away_team = row["away_team"]

    team_goals.setdefault(home_team, {"goals_scored": 0, "matches": 0})
    team_goals.setdefault(away_team, {"goals_scored": 0, "matches": 0})

    team_goals[home_team]["goals_scored"] += row["home_score"]
    team_goals[home_team]["matches"] += 1

    team_goals[away_team]["goals_scored"] += row["away_score"]
    team_goals[away_team]["matches"] += 1


team_avg_goals_scored = {
    team: stats["goals_scored"] / stats["matches"]
    for team, stats in team_goals.items()
}

# =========================
# 2. Add features
# =========================

df_features_goals = df_features.copy()

df_features_goals["home_team_avg_goals_scored"] = (
    df_features_goals["home_team"]
    .map(team_avg_goals_scored)
    .fillna(1.3)
)

df_features_goals["away_team_avg_goals_scored"] = (
    df_features_goals["away_team"]
    .map(team_avg_goals_scored)
    .fillna(1.3)
)

# =========================
# 3. Build feature matrix
# =========================

X_goals = df_features_goals[
    [
        "home_team",
        "away_team",
        "tournament",
        "country",
        "neutral",
        "year",
        "home_team_win_rate",
        "away_team_win_rate",
        "home_team_avg_goals_scored",
        "away_team_avg_goals_scored",
    ]
]

y_goals = df_features_goals["result"]

X_goals_encoded = pd.get_dummies(
    X_goals,
    columns=[
        "home_team",
        "away_team",
        "tournament",
        "country"
    ]
)

# =========================
# 4. Chronological split
# =========================

train_mask = df_features_goals["year"] <= 2020
test_mask = df_features_goals["year"] > 2020

X_train_goals = X_goals_encoded[train_mask]
X_test_goals = X_goals_encoded[test_mask]

y_train_goals = y_goals[train_mask]
y_test_goals = y_goals[test_mask]

# =========================
# 5. Train model
# =========================

rf_goals = RandomForestClassifier(random_state=42)

rf_goals.fit(X_train_goals, y_train_goals)

y_pred_goals = rf_goals.predict(X_test_goals)

accuracy_goals = accuracy_score(y_test_goals, y_pred_goals)

print("Accuracy WITH win-rate + avg goals scored:", accuracy_goals)
print(classification_report(y_test_goals, y_pred_goals))

Accuracy WITH win-rate + avg goals scored: 0.5424619156014708
              precision    recall  f1-score   support

    Away Win       0.53      0.50      0.52      1662
        Draw       0.28      0.17      0.21      1308
    Home Win       0.61      0.74      0.67      2741

    accuracy                           0.54      5711
   macro avg       0.47      0.47      0.47      5711
weighted avg       0.51      0.54      0.52      5711

In [78]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

# =========================
# 1. Compute avg goals conceded using TRAINING DATA ONLY
# =========================

train_df = df_clean[df_clean["year"] <= 2020].copy()

team_conceded = {}

for _, row in train_df.iterrows():
    home_team = row["home_team"]
    away_team = row["away_team"]

    team_conceded.setdefault(home_team, {"goals_conceded": 0, "matches": 0})
    team_conceded.setdefault(away_team, {"goals_conceded": 0, "matches": 0})

    # Home team conceded away_score
    team_conceded[home_team]["goals_conceded"] += row["away_score"]
    team_conceded[home_team]["matches"] += 1

    # Away team conceded home_score
    team_conceded[away_team]["goals_conceded"] += row["home_score"]
    team_conceded[away_team]["matches"] += 1


team_avg_goals_conceded = {
    team: stats["goals_conceded"] / stats["matches"]
    for team, stats in team_conceded.items()
}

# =========================
# 2. Add conceded features
# =========================

df_features_full = df_features_goals.copy()

df_features_full["home_team_avg_goals_conceded"] = (
    df_features_full["home_team"]
    .map(team_avg_goals_conceded)
    .fillna(1.3)
)

df_features_full["away_team_avg_goals_conceded"] = (
    df_features_full["away_team"]
    .map(team_avg_goals_conceded)
    .fillna(1.3)
)

# =========================
# 3. Build feature matrix
# =========================

X_full = df_features_full[
    [
        "home_team",
        "away_team",
        "tournament",
        "country",
        "neutral",
        "year",
        "home_team_win_rate",
        "away_team_win_rate",
        "home_team_avg_goals_scored",
        "away_team_avg_goals_scored",
        "home_team_avg_goals_conceded",
        "away_team_avg_goals_conceded",
    ]
]

y_full = df_features_full["result"]

X_full_encoded = pd.get_dummies(
    X_full,
    columns=[
        "home_team",
        "away_team",
        "tournament",
        "country"
    ]
)

# =========================
# 4. Chronological split
# =========================

train_mask = df_features_full["year"] <= 2020
test_mask = df_features_full["year"] > 2020

X_train_full = X_full_encoded[train_mask]
X_test_full = X_full_encoded[test_mask]

y_train_full = y_full[train_mask]
y_test_full = y_full[test_mask]

# =========================
# 5. Train model
# =========================

rf_full = RandomForestClassifier(random_state=42)

rf_full.fit(X_train_full, y_train_full)

y_pred_full = rf_full.predict(X_test_full)

accuracy_full = accuracy_score(y_test_full, y_pred_full)

print("Accuracy WITH win-rate + goals scored + goals conceded:", accuracy_full)
print(classification_report(y_test_full, y_pred_full))

Accuracy WITH win-rate + goals scored + goals conceded: 0.5503414463316407
              precision    recall  f1-score   support

    Away Win       0.54      0.51      0.52      1662
        Draw       0.29      0.17      0.22      1308
    Home Win       0.62      0.75      0.68      2741

    accuracy                           0.55      5711
   macro avg       0.48      0.48      0.47      5711
weighted avg       0.52      0.55      0.53      5711

In [79]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

# =========================
# 1. Add goal difference features
# =========================

df_features_gd = df_features_full.copy()

df_features_gd["home_team_goal_difference"] = (
    df_features_gd["home_team_avg_goals_scored"]
    - df_features_gd["home_team_avg_goals_conceded"]
)

df_features_gd["away_team_goal_difference"] = (
    df_features_gd["away_team_avg_goals_scored"]
    - df_features_gd["away_team_avg_goals_conceded"]
)

# =========================
# 2. Build feature matrix
# =========================

X_gd = df_features_gd[
    [
        "home_team",
        "away_team",
        "tournament",
        "country",
        "neutral",
        "year",
        "home_team_win_rate",
        "away_team_win_rate",
        "home_team_avg_goals_scored",
        "away_team_avg_goals_scored",
        "home_team_avg_goals_conceded",
        "away_team_avg_goals_conceded",
        "home_team_goal_difference",
        "away_team_goal_difference",
    ]
]

y_gd = df_features_gd["result"]

X_gd_encoded = pd.get_dummies(
    X_gd,
    columns=[
        "home_team",
        "away_team",
        "tournament",
        "country"
    ]
)

# =========================
# 3. Chronological split
# =========================

train_mask = df_features_gd["year"] <= 2020
test_mask = df_features_gd["year"] > 2020

X_train_gd = X_gd_encoded[train_mask]
X_test_gd = X_gd_encoded[test_mask]

y_train_gd = y_gd[train_mask]
y_test_gd = y_gd[test_mask]

# =========================
# 4. Train model
# =========================

rf_gd = RandomForestClassifier(random_state=42)

rf_gd.fit(X_train_gd, y_train_gd)

y_pred_gd = rf_gd.predict(X_test_gd)

accuracy_gd = accuracy_score(y_test_gd, y_pred_gd)

print("Accuracy WITH goal difference:", accuracy_gd)
print(classification_report(y_test_gd, y_pred_gd))

Accuracy WITH goal difference: 0.5443880231132902
              precision    recall  f1-score   support

    Away Win       0.53      0.51      0.52      1662
        Draw       0.28      0.18      0.22      1308
    Home Win       0.62      0.74      0.67      2741

    accuracy                           0.54      5711
   macro avg       0.48      0.48      0.47      5711
weighted avg       0.51      0.54      0.52      5711

In [80]:
from collections import defaultdict
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

# ==================================================
# RECENT FORM (last 10 matches approximation)
# ==================================================

train_df = df_clean[df_clean["year"] <= 2020].copy()

team_results = defaultdict(list)

for _, row in train_df.iterrows():

    home_team = row["home_team"]
    away_team = row["away_team"]

    # Home team result
    if row["result"] == "Home Win":
        team_results[home_team].append(1)
        team_results[away_team].append(0)

    elif row["result"] == "Away Win":
        team_results[home_team].append(0)
        team_results[away_team].append(1)

    else:
        team_results[home_team].append(0.5)
        team_results[away_team].append(0.5)

# Average of last 10 matches
recent_form = {}

for team, results in team_results.items():

    last_10 = results[-10:]

    recent_form[team] = sum(last_10) / len(last_10)

# ==================================================
# ADD FEATURES
# ==================================================

df_recent = df_features_full.copy()

df_recent["home_recent_form"] = (
    df_recent["home_team"]
    .map(recent_form)
    .fillna(0.5)
)

df_recent["away_recent_form"] = (
    df_recent["away_team"]
    .map(recent_form)
    .fillna(0.5)
)

# ==================================================
# FEATURES
# ==================================================

X_recent = df_recent[
    [
        "home_team",
        "away_team",
        "tournament",
        "country",
        "neutral",
        "year",
        "home_team_win_rate",
        "away_team_win_rate",
        "home_team_avg_goals_scored",
        "away_team_avg_goals_scored",
        "home_team_avg_goals_conceded",
        "away_team_avg_goals_conceded",
        "home_recent_form",
        "away_recent_form",
    ]
]

y_recent = df_recent["result"]

X_recent_encoded = pd.get_dummies(
    X_recent,
    columns=[
        "home_team",
        "away_team",
        "tournament",
        "country"
    ]
)

# ==================================================
# SPLIT
# ==================================================

train_mask = df_recent["year"] <= 2020
test_mask = df_recent["year"] > 2020

X_train_recent = X_recent_encoded[train_mask]
X_test_recent = X_recent_encoded[test_mask]

y_train_recent = y_recent[train_mask]
y_test_recent = y_recent[test_mask]

# ==================================================
# MODEL
# ==================================================

rf_recent = RandomForestClassifier(random_state=42)

rf_recent.fit(X_train_recent, y_train_recent)

y_pred_recent = rf_recent.predict(X_test_recent)

accuracy_recent = accuracy_score(
    y_test_recent,
    y_pred_recent
)

print("Accuracy WITH recent form:", accuracy_recent)

print(
    classification_report(
        y_test_recent,
        y_pred_recent
    )
)

Accuracy WITH recent form: 0.5436876203817195
              precision    recall  f1-score   support

    Away Win       0.53      0.50      0.52      1662
        Draw       0.28      0.18      0.22      1308
    Home Win       0.61      0.75      0.67      2741

    accuracy                           0.54      5711
   macro avg       0.48      0.47      0.47      5711
weighted avg       0.51      0.54      0.52      5711

In [82]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import StandardScaler

# Copy data
X_train_lr_scaled = X_train_lr.copy()
X_test_lr_scaled = X_test_lr.copy()

# Numerical columns to scale
num_cols = [
    "year",
    "home_team_win_rate",
    "away_team_win_rate",
    "home_team_avg_goals_scored",
    "away_team_avg_goals_scored",
    "home_team_avg_goals_conceded",
    "away_team_avg_goals_conceded",
]

# Scale numerical columns
scaler = StandardScaler()

X_train_lr_scaled[num_cols] = scaler.fit_transform(X_train_lr_scaled[num_cols])
X_test_lr_scaled[num_cols] = scaler.transform(X_test_lr_scaled[num_cols])

# Logistic Regression model
lr_model = LogisticRegression(
    max_iter=5000,
    random_state=42
)

lr_model.fit(X_train_lr_scaled, y_train_lr)

y_pred_lr = lr_model.predict(X_test_lr_scaled)

accuracy_lr = accuracy_score(y_test_lr, y_pred_lr)

print("Logistic Regression Accuracy:", accuracy_lr)
print(classification_report(y_test_lr, y_pred_lr))

Logistic Regression Accuracy: 0.5895639992995972
              precision    recall  f1-score   support

    Away Win       0.57      0.55      0.56      1662
        Draw       0.33      0.12      0.17      1308
    Home Win       0.63      0.84      0.72      2741

    accuracy                           0.59      5711
   macro avg       0.51      0.50      0.49      5711
weighted avg       0.54      0.59      0.55      5711

In [85]:
import pandas as pd

leaderboard = pd.DataFrame(
    {
        "Rank": [
             "4",
             "3",
             "2",
             "1"
        ],
        "Model": [
            "Decision Tree",
            "Random Forest",
            "Random Forest + Features",
            "Logistic Regression"
        ],
        "Accuracy": [
            0.4234,
            0.5285,
            0.5503,
            0.5896
        ]
    }
)

leaderboard = leaderboard.sort_values(
    by="Accuracy",
    ascending=False
)

leaderboard

  Rank                     Model  Accuracy
3    1       Logistic Regression    0.5896
2    2  Random Forest + Features    0.5503
1    3             Random Forest    0.5285
0    4             Decision Tree    0.4234